name: Build and Push to Quay.io

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Quay.io
        run: echo "${{ secrets.QUAY_PASSWORD }}" | docker login quay.io -u "${{ secrets.QUAY_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t quay.io/${{ secrets.QUAY_USERNAME }}/mavenjdk:latest .

      - name: Push Docker Image to Quay.io
        run: docker push quay.io/${{ secrets.QUAY_USERNAME }}/mavenjdk:latest
