name: Build and Push to Quay.io

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest #GitHub Actions tumhare workflows ko execute karne ke liye latest version of Ubuntu ka VM use karta hai.

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Quay.io
        run: echo "Pritam@#845980" | docker login quay.io -u "nitinpallelwar" --password-stdin #Iska matlab hai ki tum password ko stdin (standard input) ke through pass kar rahe ho, instead of directly command line me likhne ke.
        
      - name: Build Docker Image
        run: docker build -t quay.io/nitinpallelwar/myrepo:latest .

      - name: Push Docker Image to Quay.io
        run: docker push quay.io/nitinpallelwar/myrepo:latest
